/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Latixel' at '06/11/15 22:06' with Gradle 2.8
 *
 * @author Latixel, @date 06/11/15 22:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static int testFunction(int a, int b){
    	return a+b;
    }    

}
