import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Latixel' at '06/11/15 22:06' with Gradle 2.8
 *
 * @author Latixel, @date 06/11/15 22:06
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testFunction(){
    	assertTrue(Library.testFunction(3, 2) == 5);
    }
    
}
